name: Push

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install plugins
        run: pip3 install mkdocs-material
      - name: Deploy docs
        run: mkdocs gh-deploy
